# Generated by Django 2.1.1 on 2018-10-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
